- name: Copy the mongodb repo
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Installing mongodb
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: starting mongodb
  ansible.builtin.systemd:
    name: mongodb
    state: started
    enabled: true
