- name: configuring Nodejs repo
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: creating {{APPUSER}} 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop application user

- name: Download and extracting the {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Generating artifacts with npm install
  community.general.npm:
    path: /home/{{ APPUSER }}/{{ COMPONENT }}/

- name: Copy the systemd file
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service    


- name: Restarting {{COMPONENT}}
  ansible.builtin.systemd:
    name: {{ COMPONENT }}
    state: restarted
    enabled: true   
    daemon_reload: true  

- name: configuring Node Name Repo
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}




   