- name: Copy the {{ COMPONENT }} repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Installing {{ COMPONENT }}
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: starting {{ COMPONENT }}
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true
  

