- name: Copy the {{ COMPONENT }} repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Installing {{ COMPONENT }}
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: starting {{ COMPONENT }}
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true
  
- name: Fetch the log file from the rmot note
  ansible.builtin.slurp:
    src: /var/log/mysqld.log
  register: mysql_pwd_log

- name: validate the default password
  block: 
    - name: Get MySQL version with non-default credentials
      community.mysql.mysql_info:
        login_user: root
        login_password: Roboshop@1
        filter: version  
  rescue:
    - name: Grep the password and assign it to a variable
      ansible.builtin.set_fact:
          DEFAULT_PASSWORD: "{{ mysql_pwd_log['content'] | b64decode | regex_findall('.*temporary password.*')| join(' ') |split(' ') | last }}"

    - name: Rest Default {{COMPONENT}} Default root password
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY 'RoboShop@1';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASSWORD}}"


    - block:
      - name: Install the nginx package
        service: name=nginx state=started
          name:
          state:
    - rescue:
      - name: Log the error
        debug:

# - name: Printing the password
#  ansible.builtin.debug:
#      msg: "Printing the pwd {{DEFAULT_PASSWORD}}"

- name: configuring Node Name Repo
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}     
