- name: Install bottle into the specified (virtualenv), inheriting globally installed modules
  ansible.builtin.pip:
      name:
        - boto3
        - botocore
      executable: pip3
      
- name: configuring Nodejs repo {{ COMPONENT }}
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: Installing Nodejs on {{ COMPONENT }}-{{ENV}} server
  ansible.builtin.package:
    name: nodejs
    state: present

- name: creating {{APPUSER}} 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop application user

# - name: Downloading the .pem file needed for NodeJS Components
#   ansible.builtin.get_url:
#     url: https://truststore.pki.rds.amazonaws.com/global/global-bundle.pem
#     dest: "/home/{{APPUSER}}/global-bundle.pem"

- name: Download and extracting the {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Generating artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring the service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: configuring Node Name Repo
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}