- name: Installing Python on {{ COMPONENT }}-{{ENV}} server
  ansible.builtin.yum:
    name: 
      - python36
      - gcc
      - python3-devel
    state: present


- name: creating {{APPUSER}} 
  ansible.builtin.user:
    name: "{{APPUSER}}"
    comment: Roboshop application user

- name: Download and extracting the {{ COMPONENT }}
  ansible.builtin.include_role:
    name: common
    tasks_from: download